// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_configuration.proto

package com.id.configuration.proto;

/**
 * Protobuf type {@code ChangeEvent}
 */
public  final class ChangeEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ChangeEvent)
    ChangeEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChangeEvent.newBuilder() to construct.
  private ChangeEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChangeEvent() {
    operation_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChangeEvent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.id.configuration.proto.ValueOption.Builder subBuilder = null;
            if (option_ != null) {
              subBuilder = option_.toBuilder();
            }
            option_ = input.readMessage(com.id.configuration.proto.ValueOption.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(option_);
              option_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            operation_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.id.configuration.proto.RemoteConfiguration.internal_static_ChangeEvent_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.id.configuration.proto.RemoteConfiguration.internal_static_ChangeEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.id.configuration.proto.ChangeEvent.class, com.id.configuration.proto.ChangeEvent.Builder.class);
  }

  public static final int OPTION_FIELD_NUMBER = 1;
  private com.id.configuration.proto.ValueOption option_;
  /**
   * <code>.ValueOption option = 1;</code>
   */
  public boolean hasOption() {
    return option_ != null;
  }
  /**
   * <code>.ValueOption option = 1;</code>
   */
  public com.id.configuration.proto.ValueOption getOption() {
    return option_ == null ? com.id.configuration.proto.ValueOption.getDefaultInstance() : option_;
  }
  /**
   * <code>.ValueOption option = 1;</code>
   */
  public com.id.configuration.proto.ValueOptionOrBuilder getOptionOrBuilder() {
    return getOption();
  }

  public static final int OPERATION_FIELD_NUMBER = 2;
  private int operation_;
  /**
   * <code>.Operation operation = 2;</code>
   */
  public int getOperationValue() {
    return operation_;
  }
  /**
   * <code>.Operation operation = 2;</code>
   */
  public com.id.configuration.proto.Operation getOperation() {
    com.id.configuration.proto.Operation result = com.id.configuration.proto.Operation.valueOf(operation_);
    return result == null ? com.id.configuration.proto.Operation.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (option_ != null) {
      output.writeMessage(1, getOption());
    }
    if (operation_ != com.id.configuration.proto.Operation.SET.getNumber()) {
      output.writeEnum(2, operation_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (option_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOption());
    }
    if (operation_ != com.id.configuration.proto.Operation.SET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, operation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.id.configuration.proto.ChangeEvent)) {
      return super.equals(obj);
    }
    com.id.configuration.proto.ChangeEvent other = (com.id.configuration.proto.ChangeEvent) obj;

    boolean result = true;
    result = result && (hasOption() == other.hasOption());
    if (hasOption()) {
      result = result && getOption()
          .equals(other.getOption());
    }
    result = result && operation_ == other.operation_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOption()) {
      hash = (37 * hash) + OPTION_FIELD_NUMBER;
      hash = (53 * hash) + getOption().hashCode();
    }
    hash = (37 * hash) + OPERATION_FIELD_NUMBER;
    hash = (53 * hash) + operation_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.id.configuration.proto.ChangeEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.id.configuration.proto.ChangeEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.id.configuration.proto.ChangeEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.id.configuration.proto.ChangeEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.id.configuration.proto.ChangeEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.id.configuration.proto.ChangeEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.id.configuration.proto.ChangeEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.id.configuration.proto.ChangeEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.id.configuration.proto.ChangeEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.id.configuration.proto.ChangeEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.id.configuration.proto.ChangeEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.id.configuration.proto.ChangeEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.id.configuration.proto.ChangeEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ChangeEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ChangeEvent)
      com.id.configuration.proto.ChangeEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.id.configuration.proto.RemoteConfiguration.internal_static_ChangeEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.id.configuration.proto.RemoteConfiguration.internal_static_ChangeEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.id.configuration.proto.ChangeEvent.class, com.id.configuration.proto.ChangeEvent.Builder.class);
    }

    // Construct using com.id.configuration.proto.ChangeEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (optionBuilder_ == null) {
        option_ = null;
      } else {
        option_ = null;
        optionBuilder_ = null;
      }
      operation_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.id.configuration.proto.RemoteConfiguration.internal_static_ChangeEvent_descriptor;
    }

    public com.id.configuration.proto.ChangeEvent getDefaultInstanceForType() {
      return com.id.configuration.proto.ChangeEvent.getDefaultInstance();
    }

    public com.id.configuration.proto.ChangeEvent build() {
      com.id.configuration.proto.ChangeEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.id.configuration.proto.ChangeEvent buildPartial() {
      com.id.configuration.proto.ChangeEvent result = new com.id.configuration.proto.ChangeEvent(this);
      if (optionBuilder_ == null) {
        result.option_ = option_;
      } else {
        result.option_ = optionBuilder_.build();
      }
      result.operation_ = operation_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.id.configuration.proto.ChangeEvent) {
        return mergeFrom((com.id.configuration.proto.ChangeEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.id.configuration.proto.ChangeEvent other) {
      if (other == com.id.configuration.proto.ChangeEvent.getDefaultInstance()) return this;
      if (other.hasOption()) {
        mergeOption(other.getOption());
      }
      if (other.operation_ != 0) {
        setOperationValue(other.getOperationValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.id.configuration.proto.ChangeEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.id.configuration.proto.ChangeEvent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.id.configuration.proto.ValueOption option_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.id.configuration.proto.ValueOption, com.id.configuration.proto.ValueOption.Builder, com.id.configuration.proto.ValueOptionOrBuilder> optionBuilder_;
    /**
     * <code>.ValueOption option = 1;</code>
     */
    public boolean hasOption() {
      return optionBuilder_ != null || option_ != null;
    }
    /**
     * <code>.ValueOption option = 1;</code>
     */
    public com.id.configuration.proto.ValueOption getOption() {
      if (optionBuilder_ == null) {
        return option_ == null ? com.id.configuration.proto.ValueOption.getDefaultInstance() : option_;
      } else {
        return optionBuilder_.getMessage();
      }
    }
    /**
     * <code>.ValueOption option = 1;</code>
     */
    public Builder setOption(com.id.configuration.proto.ValueOption value) {
      if (optionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        option_ = value;
        onChanged();
      } else {
        optionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ValueOption option = 1;</code>
     */
    public Builder setOption(
        com.id.configuration.proto.ValueOption.Builder builderForValue) {
      if (optionBuilder_ == null) {
        option_ = builderForValue.build();
        onChanged();
      } else {
        optionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ValueOption option = 1;</code>
     */
    public Builder mergeOption(com.id.configuration.proto.ValueOption value) {
      if (optionBuilder_ == null) {
        if (option_ != null) {
          option_ =
            com.id.configuration.proto.ValueOption.newBuilder(option_).mergeFrom(value).buildPartial();
        } else {
          option_ = value;
        }
        onChanged();
      } else {
        optionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ValueOption option = 1;</code>
     */
    public Builder clearOption() {
      if (optionBuilder_ == null) {
        option_ = null;
        onChanged();
      } else {
        option_ = null;
        optionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ValueOption option = 1;</code>
     */
    public com.id.configuration.proto.ValueOption.Builder getOptionBuilder() {
      
      onChanged();
      return getOptionFieldBuilder().getBuilder();
    }
    /**
     * <code>.ValueOption option = 1;</code>
     */
    public com.id.configuration.proto.ValueOptionOrBuilder getOptionOrBuilder() {
      if (optionBuilder_ != null) {
        return optionBuilder_.getMessageOrBuilder();
      } else {
        return option_ == null ?
            com.id.configuration.proto.ValueOption.getDefaultInstance() : option_;
      }
    }
    /**
     * <code>.ValueOption option = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.id.configuration.proto.ValueOption, com.id.configuration.proto.ValueOption.Builder, com.id.configuration.proto.ValueOptionOrBuilder> 
        getOptionFieldBuilder() {
      if (optionBuilder_ == null) {
        optionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.id.configuration.proto.ValueOption, com.id.configuration.proto.ValueOption.Builder, com.id.configuration.proto.ValueOptionOrBuilder>(
                getOption(),
                getParentForChildren(),
                isClean());
        option_ = null;
      }
      return optionBuilder_;
    }

    private int operation_ = 0;
    /**
     * <code>.Operation operation = 2;</code>
     */
    public int getOperationValue() {
      return operation_;
    }
    /**
     * <code>.Operation operation = 2;</code>
     */
    public Builder setOperationValue(int value) {
      operation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Operation operation = 2;</code>
     */
    public com.id.configuration.proto.Operation getOperation() {
      com.id.configuration.proto.Operation result = com.id.configuration.proto.Operation.valueOf(operation_);
      return result == null ? com.id.configuration.proto.Operation.UNRECOGNIZED : result;
    }
    /**
     * <code>.Operation operation = 2;</code>
     */
    public Builder setOperation(com.id.configuration.proto.Operation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      operation_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Operation operation = 2;</code>
     */
    public Builder clearOperation() {
      
      operation_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ChangeEvent)
  }

  // @@protoc_insertion_point(class_scope:ChangeEvent)
  private static final com.id.configuration.proto.ChangeEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.id.configuration.proto.ChangeEvent();
  }

  public static com.id.configuration.proto.ChangeEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChangeEvent>
      PARSER = new com.google.protobuf.AbstractParser<ChangeEvent>() {
    public ChangeEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangeEvent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChangeEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChangeEvent> getParserForType() {
    return PARSER;
  }

  public com.id.configuration.proto.ChangeEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

