// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_configuration.proto

package com.id.configuration.proto;

public interface LevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Level)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 level = 1;</code>
   */
  int getLevel();
}
