// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_configuration.proto

package com.id.configuration.proto;

public interface NameListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NameList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Option namelist = 1;</code>
   */
  java.util.List<com.id.configuration.proto.Option> 
      getNamelistList();
  /**
   * <code>repeated .Option namelist = 1;</code>
   */
  com.id.configuration.proto.Option getNamelist(int index);
  /**
   * <code>repeated .Option namelist = 1;</code>
   */
  int getNamelistCount();
  /**
   * <code>repeated .Option namelist = 1;</code>
   */
  java.util.List<? extends com.id.configuration.proto.OptionOrBuilder> 
      getNamelistOrBuilderList();
  /**
   * <code>repeated .Option namelist = 1;</code>
   */
  com.id.configuration.proto.OptionOrBuilder getNamelistOrBuilder(
      int index);
}
