// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_configuration.proto

package com.id.configuration.proto;

/**
 * Protobuf type {@code NameList}
 */
public  final class NameList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NameList)
    NameListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NameList.newBuilder() to construct.
  private NameList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NameList() {
    namelist_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NameList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              namelist_ = new java.util.ArrayList<com.id.configuration.proto.Option>();
              mutable_bitField0_ |= 0x00000001;
            }
            namelist_.add(
                input.readMessage(com.id.configuration.proto.Option.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        namelist_ = java.util.Collections.unmodifiableList(namelist_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.id.configuration.proto.RemoteConfiguration.internal_static_NameList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.id.configuration.proto.RemoteConfiguration.internal_static_NameList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.id.configuration.proto.NameList.class, com.id.configuration.proto.NameList.Builder.class);
  }

  public static final int NAMELIST_FIELD_NUMBER = 1;
  private java.util.List<com.id.configuration.proto.Option> namelist_;
  /**
   * <code>repeated .Option namelist = 1;</code>
   */
  public java.util.List<com.id.configuration.proto.Option> getNamelistList() {
    return namelist_;
  }
  /**
   * <code>repeated .Option namelist = 1;</code>
   */
  public java.util.List<? extends com.id.configuration.proto.OptionOrBuilder> 
      getNamelistOrBuilderList() {
    return namelist_;
  }
  /**
   * <code>repeated .Option namelist = 1;</code>
   */
  public int getNamelistCount() {
    return namelist_.size();
  }
  /**
   * <code>repeated .Option namelist = 1;</code>
   */
  public com.id.configuration.proto.Option getNamelist(int index) {
    return namelist_.get(index);
  }
  /**
   * <code>repeated .Option namelist = 1;</code>
   */
  public com.id.configuration.proto.OptionOrBuilder getNamelistOrBuilder(
      int index) {
    return namelist_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < namelist_.size(); i++) {
      output.writeMessage(1, namelist_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < namelist_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, namelist_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.id.configuration.proto.NameList)) {
      return super.equals(obj);
    }
    com.id.configuration.proto.NameList other = (com.id.configuration.proto.NameList) obj;

    boolean result = true;
    result = result && getNamelistList()
        .equals(other.getNamelistList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNamelistCount() > 0) {
      hash = (37 * hash) + NAMELIST_FIELD_NUMBER;
      hash = (53 * hash) + getNamelistList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.id.configuration.proto.NameList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.id.configuration.proto.NameList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.id.configuration.proto.NameList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.id.configuration.proto.NameList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.id.configuration.proto.NameList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.id.configuration.proto.NameList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.id.configuration.proto.NameList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.id.configuration.proto.NameList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.id.configuration.proto.NameList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.id.configuration.proto.NameList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.id.configuration.proto.NameList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.id.configuration.proto.NameList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.id.configuration.proto.NameList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code NameList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NameList)
      com.id.configuration.proto.NameListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.id.configuration.proto.RemoteConfiguration.internal_static_NameList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.id.configuration.proto.RemoteConfiguration.internal_static_NameList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.id.configuration.proto.NameList.class, com.id.configuration.proto.NameList.Builder.class);
    }

    // Construct using com.id.configuration.proto.NameList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNamelistFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (namelistBuilder_ == null) {
        namelist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        namelistBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.id.configuration.proto.RemoteConfiguration.internal_static_NameList_descriptor;
    }

    public com.id.configuration.proto.NameList getDefaultInstanceForType() {
      return com.id.configuration.proto.NameList.getDefaultInstance();
    }

    public com.id.configuration.proto.NameList build() {
      com.id.configuration.proto.NameList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.id.configuration.proto.NameList buildPartial() {
      com.id.configuration.proto.NameList result = new com.id.configuration.proto.NameList(this);
      int from_bitField0_ = bitField0_;
      if (namelistBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          namelist_ = java.util.Collections.unmodifiableList(namelist_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.namelist_ = namelist_;
      } else {
        result.namelist_ = namelistBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.id.configuration.proto.NameList) {
        return mergeFrom((com.id.configuration.proto.NameList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.id.configuration.proto.NameList other) {
      if (other == com.id.configuration.proto.NameList.getDefaultInstance()) return this;
      if (namelistBuilder_ == null) {
        if (!other.namelist_.isEmpty()) {
          if (namelist_.isEmpty()) {
            namelist_ = other.namelist_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNamelistIsMutable();
            namelist_.addAll(other.namelist_);
          }
          onChanged();
        }
      } else {
        if (!other.namelist_.isEmpty()) {
          if (namelistBuilder_.isEmpty()) {
            namelistBuilder_.dispose();
            namelistBuilder_ = null;
            namelist_ = other.namelist_;
            bitField0_ = (bitField0_ & ~0x00000001);
            namelistBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNamelistFieldBuilder() : null;
          } else {
            namelistBuilder_.addAllMessages(other.namelist_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.id.configuration.proto.NameList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.id.configuration.proto.NameList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.id.configuration.proto.Option> namelist_ =
      java.util.Collections.emptyList();
    private void ensureNamelistIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        namelist_ = new java.util.ArrayList<com.id.configuration.proto.Option>(namelist_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.id.configuration.proto.Option, com.id.configuration.proto.Option.Builder, com.id.configuration.proto.OptionOrBuilder> namelistBuilder_;

    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public java.util.List<com.id.configuration.proto.Option> getNamelistList() {
      if (namelistBuilder_ == null) {
        return java.util.Collections.unmodifiableList(namelist_);
      } else {
        return namelistBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public int getNamelistCount() {
      if (namelistBuilder_ == null) {
        return namelist_.size();
      } else {
        return namelistBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public com.id.configuration.proto.Option getNamelist(int index) {
      if (namelistBuilder_ == null) {
        return namelist_.get(index);
      } else {
        return namelistBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public Builder setNamelist(
        int index, com.id.configuration.proto.Option value) {
      if (namelistBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamelistIsMutable();
        namelist_.set(index, value);
        onChanged();
      } else {
        namelistBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public Builder setNamelist(
        int index, com.id.configuration.proto.Option.Builder builderForValue) {
      if (namelistBuilder_ == null) {
        ensureNamelistIsMutable();
        namelist_.set(index, builderForValue.build());
        onChanged();
      } else {
        namelistBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public Builder addNamelist(com.id.configuration.proto.Option value) {
      if (namelistBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamelistIsMutable();
        namelist_.add(value);
        onChanged();
      } else {
        namelistBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public Builder addNamelist(
        int index, com.id.configuration.proto.Option value) {
      if (namelistBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamelistIsMutable();
        namelist_.add(index, value);
        onChanged();
      } else {
        namelistBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public Builder addNamelist(
        com.id.configuration.proto.Option.Builder builderForValue) {
      if (namelistBuilder_ == null) {
        ensureNamelistIsMutable();
        namelist_.add(builderForValue.build());
        onChanged();
      } else {
        namelistBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public Builder addNamelist(
        int index, com.id.configuration.proto.Option.Builder builderForValue) {
      if (namelistBuilder_ == null) {
        ensureNamelistIsMutable();
        namelist_.add(index, builderForValue.build());
        onChanged();
      } else {
        namelistBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public Builder addAllNamelist(
        java.lang.Iterable<? extends com.id.configuration.proto.Option> values) {
      if (namelistBuilder_ == null) {
        ensureNamelistIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, namelist_);
        onChanged();
      } else {
        namelistBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public Builder clearNamelist() {
      if (namelistBuilder_ == null) {
        namelist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        namelistBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public Builder removeNamelist(int index) {
      if (namelistBuilder_ == null) {
        ensureNamelistIsMutable();
        namelist_.remove(index);
        onChanged();
      } else {
        namelistBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public com.id.configuration.proto.Option.Builder getNamelistBuilder(
        int index) {
      return getNamelistFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public com.id.configuration.proto.OptionOrBuilder getNamelistOrBuilder(
        int index) {
      if (namelistBuilder_ == null) {
        return namelist_.get(index);  } else {
        return namelistBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public java.util.List<? extends com.id.configuration.proto.OptionOrBuilder> 
         getNamelistOrBuilderList() {
      if (namelistBuilder_ != null) {
        return namelistBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(namelist_);
      }
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public com.id.configuration.proto.Option.Builder addNamelistBuilder() {
      return getNamelistFieldBuilder().addBuilder(
          com.id.configuration.proto.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public com.id.configuration.proto.Option.Builder addNamelistBuilder(
        int index) {
      return getNamelistFieldBuilder().addBuilder(
          index, com.id.configuration.proto.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .Option namelist = 1;</code>
     */
    public java.util.List<com.id.configuration.proto.Option.Builder> 
         getNamelistBuilderList() {
      return getNamelistFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.id.configuration.proto.Option, com.id.configuration.proto.Option.Builder, com.id.configuration.proto.OptionOrBuilder> 
        getNamelistFieldBuilder() {
      if (namelistBuilder_ == null) {
        namelistBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.id.configuration.proto.Option, com.id.configuration.proto.Option.Builder, com.id.configuration.proto.OptionOrBuilder>(
                namelist_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        namelist_ = null;
      }
      return namelistBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NameList)
  }

  // @@protoc_insertion_point(class_scope:NameList)
  private static final com.id.configuration.proto.NameList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.id.configuration.proto.NameList();
  }

  public static com.id.configuration.proto.NameList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NameList>
      PARSER = new com.google.protobuf.AbstractParser<NameList>() {
    public NameList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new NameList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NameList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NameList> getParserForType() {
    return PARSER;
  }

  public com.id.configuration.proto.NameList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

