// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_configuration.proto

package com.id.configuration.proto;

public interface OptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Option)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>int32 level = 2;</code>
   */
  int getLevel();
}
