// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_configuration.proto

package com.id.configuration.proto;

public interface TypedOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TypedOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>int32 level = 2;</code>
   */
  int getLevel();

  /**
   * <code>.Type type = 3;</code>
   */
  int getTypeValue();
  /**
   * <code>.Type type = 3;</code>
   */
  com.id.configuration.proto.Type getType();
}
